name: E-commerce website

on: 
 push:
   branches:
     - main

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout
       uses: actions/checkout@v6.0.3
     - name: Setup Node.js environment
       uses: actions/setup-node@v6.4.0
       with:
         node-version : 22.x
         cache: npm
         cache-dependency-path: Frontend/package-lock.json
         
     - name: Install Frontend Dependencies
       working-directory: Frontend
       run : npm install

     - name: Build-Frontend
       working-directory: Frontend
       run : npm run build

     - name: Install Backend Dependencies
       working-directory: Backend
       run: npm install

     - name: Test Backend
       working-directory: Backend
       run: npm test

     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v7.0.1  
       with : 
         name : react-build
         path : Frontend/dist
       
